project:
  type: website
  output-dir: docs

website:
  title: ""
  search: true
  sidebar: false
  navbar: false

format:
  html:
    theme: darkly
    css: styles.css
    toc: false
    page-layout: full



